apiVersion: v1
kind: Secret
metadata:
  name: podmart-secrets
  namespace: podmart
type: Opaque
stringData:
  POSTGRES_USER: "podmart"
  POSTGRES_PASSWORD: "podmart123"
  PRODUCT_DB_URL: "postgresql://podmart:podmart123@product-db:5432/productdb"
  ORDER_DB_URL: "postgresql://podmart:podmart123@order-db:5432/orderdb"
  USER_DB_URL: "postgresql://podmart:podmart123@user-db:5432/userdb"
