apiVersion: v1
kind: Secret
metadata:
  name: podmart-secrets
  namespace: podmart
type: Opaque
stringData:
  POSTGRES_USER: "changeme"
  POSTGRES_PASSWORD: "changeme"
  PRODUCT_DB_URL: "postgresql://user:password@product-db:5432/productdb"
  ORDER_DB_URL: "postgresql://user:password@order-db:5432/orderdb"
  USER_DB_URL: "postgresql://user:password@user-db:5432/userdb"
