apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: product-db
  namespace: podmart
spec:
  serviceName: product-db
  replicas: 1
  selector:
    matchLabels:
      app: product-db
  template:
    metadata:
      labels:
        app: product-db
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "productdb"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: podmart-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: podmart-secrets
              key: POSTGRES_PASSWORD
        volumeMounts:
        - name: product-db-storage
          mountPath: /var/lib/postgresql/data
        readinessProbe:
          exec:
            command: ["pg_isready", "-U", "podmart", "-d", "productdb"]
          initialDelaySeconds: 10
          periodSeconds: 5
  volumeClaimTemplates:
  - metadata:
      name: product-db-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: product-db
  namespace: podmart
spec:
  selector:
    app: product-db
  ports:
  - port: 5432
    targetPort: 5432
  clusterIP: None
